version: '3'
services:
  mysql:
    image: mysql:8.0.17
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    user: "1000:1000"
    ports:
    - "33060:33060"
    env_file: .env
    volumes:
    - ./dbdata:/var/lib/mysql
    - ./mysql_conf/my.cnf:/etc/mysql/my.cnf
    #  - ./sqlmnt:/docker-entrypoint-initdb.d

  adminer:
    image: adminer:4.7.2
    restart: always
    depends_on:
        - mysql
    ports:
    - "8888:8080"

