version: '3'
services:
  mysql:
    image: mysql:8.0.17
    restart: always
    ports:
    - "3306:3306"
    env_file: .env
    volumes:
    - "./dbdata:/var/lib/mysql"
    - "./mysql_conf:/etc/mysql"
    #  - ./sqlmnt:/docker-entrypoint-initdb.d
  adminer:
    image: adminer:4.7.2
    restart: always
    depends_on:
        - mysql
    ports:
    - "8888:8080"
