version: '3'
services:
  mysql:
    image: mysql:8.0.17
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    env_file: .env
    volumes:
    - ./dbdata:/var/lib/mysql
    - ./mysql_conf/my.cnf:/etc/mysql/my.cnf
    #  - ./sqlmnt:/docker-entrypoint-initdb.d
    networks:
      - web

  adminer:
    image: adminer:4.7.2
    restart: always
    depends_on:
        - mysql
    ports:
    - "8888:8080"
    networks:
      - web
  nginx:
    image: nginx: 
nginx:
  image: nginx:1.16-alpine
  restart: always
  volumes:
  - /var/www/html:/usr/share/nginx/html
  - ./nginx_conf/nginx.conf:/etc/nginx/nginx.conf
  ports:
  - "80:80"
  - "443:443" 
  networks:
    - web

networks:
  web:
